### PR TITLE
Remove "how to update an operator" doc

### PR DESCRIPTION
**Pull request by anik120**
The "how to update an operator doc" talks about updating a
catalogsource to receive updates to your operator in the pre
catalogsource polling era. Receiving updates to catalogsources
will be covered in explanation of catalogsource polling feature
in another doc.

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by anik120** [comment]
Leaving this PR open for now since there is a potential change of strategy around the releases of OLM we want to have docs for, and this work should be revisited when that strategy is implemented.

**Pull request merged**
